// react-hooks-typescript/src/App.tsx
import { ChangeEvent, useState, useEffect, useRef } from 'react';
import './App.scss';

//custom Hook
function usePrevious(value: number) {
  const ref = useRef<number>(0);
  useEffect(() => {
    ref.current = value;
  }, [value]);
  return ref.current;
}

const Counter = () => {
  const [count, setCount] = useState(0);

  const inc = (count: number) => count + 1;
  const dec = (count: number) => count - 1;
  const changeCount = (event: ChangeEvent<HTMLInputElement>) => {
    setCount(+event.target.value);
  };

  const prevCount = usePrevious(count);

  useEffect(() => {
    console.log('The old counter value is: ' + prevCount);
    console.log('The new counter value is: ' + count);
  }, [prevCount, count]);

  return (
    <main className="Counter">
      <h1>Days Since Last Incident</h1>
      <p className="count">{count}</p>
      <section className="controls">
        <button onClick={() => setCount(inc)}>Increment</button>
        <button onClick={() => setCount(0)}>Reset</button>
        <button onClick={() => setCount(dec)}>Decrement</button>
      </section>
      <section className="controls">
        <form onSubmit={() => {}}>
          <label htmlFor="set-to">Set Count</label>
          <input
            id="set-to"
            type="number"
            value={count}
            onChange={changeCount}
          />
        </form>
      </section>
    </main>
  );
};

const App = () => <Counter />;

export default App;

// vue3-typescript/src/App.vue
<script setup lang="ts">
import { ref, watch, watchEffect } from 'vue';

const count = ref<number>(0);
const inc = () => ++count.value;
const dec = () => --count.value;
const reset = () => {
    count.value = 0;
};

watch(count, (newValue: number, oldValue: number) => {
    console.log('The old counter value is: ' + oldValue);
    console.log('The new counter value is: ' + newValue); // 或：console.log("The new counter value is: " + count.value);
});

/*     watchEffect(() => {
      // 这个副作用在 DOM 更新之前运行，因此，模板引用还没有持有对元素的引用。
      console.log("The new counter value is: " + count.value);
    }); */
</script>

<template>
    <main class="Counter">
        <h1>Days Since Last Incident</h1>
        <p class="count">{{ count }}</p>
        <section class="controls">
            <button @click="inc">Increment</button>
            <button @click="reset">Reset</button>
            <button @click="dec">Decrement</button>
        </section>
        <section class="controls">
            <form @submit.prevent="() => {}">
                <label htmlFor="set-to">Set Count</label>
                <input id="set-to" type="number" v-model="count" />
            </form>
        </section>
    </main>
</template>

<style lang="scss" scoped>
@import '@/assets/App.scss';
</style>
